### ISSUE TITLE
SPH or FLIP?

### ISSUE THREAD

**Issue by sschwindt** [mushe/NiagaraFluid#1]
The Readme talks about SPH, but Unreal developers say Niagara Fluids is based on FLIP. Please provide clarification, if possible also, how resolution or viscosity are handled.

**Comment by mushe** [comment]
This repository is not associated with "Niagara Fluids". This repository was created before Epic's "Niagara Fluids" was added to engine and uses SPH.  I did not know even the name "Niagara Fluids" that time.

**Comment by mushe** [comment]
I updated Readme.

**Comment by sschwindt** [comment]
Thanks for clarifying.
